name: rincon_futbolero
description: Liga Veteranos Chinantla - Rincon Futbolero
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.5
